on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Run a one-line script
    steps:
      - name: Hello world action step
        id: hello
        uses: actions/hubinter@v1
        with:
          who-to-greet: 'Octat'
      - name: Get the output time
        run: echo "the time was ${{steps.hubinter.outputs.time }}"
